export enum NzlRegionalGeocodeAttribute {
    FrontOfPropertyNztmXCoordinate = "front_of_property_nztm_x_coordinate",
    FrontOfPropertyNztmYCoordinate = "front_of_property_nztm_y_coordinate",
    CentroidOfPropertyNztmXCoordinate = "centroid_of_property_nztm_x_coordinate",
    CentroidOfPropertyNztmYCoordinate = "centroid_of_property_nztm_y_coordinate",
    LinzParcelId = "linz_parcel_id",
    PropertyPurposeType = "property_purpose_type",
    Addressable = "addressable",
    MeshBlockCode = "mesh_block_code",
    TerritorialAuthorityCode = "territorial_authority_code",
    TerritorialAuthorityName = "territorial_authority_name",
    RegionalCouncilCode = "regional_council_code",
    RegionalCouncilName = "regional_council_name",
    GeneralElectorateCode = "general_electorate_code",
    GeneralElectorateName = "general_electorate_name",
    MaoriElectorateCode = "maori_electorate_code",
    MaoriElectorateName = "maori_electorate_name",
    FrontOfPropertyLatitude = "front_of_property_latitude",
    FrontOfPropertyLongitude = "front_of_property_longitude",
    CentroidOfPropertyLatitude = "centroid_of_property_latitude",
    CentroidOfPropertyLongitude = "centroid_of_property_longitude",
    MatchLevel = "match_level"
}
