package com.experian.dvs.client.common;

import java.util.HashMap;
import java.util.Map;

public enum Country {
    UNKNOWN("Unknown", "Unknown", "Unknown"),
    AFGHANISTAN("Afghanistan", "AF", "AFG"),
    ALBANIA("Albania", "AL", "ALB"),
    ALGERIA("Algeria", "DZ", "DZA"),
    AMERICAN_SAMOA("American Samoa", "AS", "ASM"),
    ANDORRA("Andorra", "AD", "AND"),
    ANGOLA("Angola", "AO", "AGO"),
    ANGUILLA("Anguilla", "AI", "AIA"),
    ANTARCTICA("Antarctica", "AQ", "ATA"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "AG", "ATG"),
    ARGENTINA("Argentina", "AR", "ARG"),
    ARMENIA("Armenia", "AM", "ARM"),
    ARUBA("Aruba", "AW", "ABW"),
    AUSTRALIA("Australia", "AU", "AUS"),
    AUSTRIA("Austria", "AT", "AUT"),
    AZERBAIJAN("Azerbaijan", "AZ", "AZE"),
    BAHAMAS("Bahamas", "BS", "BHS"),
    BAHRAIN("Bahrain", "BH", "BHR"),
    BANGLADESH("Bangladesh", "BD", "BGD"),
    BARBADOS("Barbados", "BB", "BRB"),
    BELARUS("Belarus", "BY", "BLR"),
    BELGIUM("Belgium", "BE", "BEL"),
    BELIZE("Belize", "BZ", "BLZ"),
    BENIN("Benin", "BJ", "BEN"),
    BERMUDA("Bermuda", "BM", "BMU"),
    BHUTAN("Bhutan", "BT", "BTN"),
    BOLIVIA("Bolivia", "BO", "BOL"),
    BONAIRE_SINT_EUSTATIUS_AND_SABA("Bonaire, Sint Eustatius and Saba", "BQ", "BES"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "BA", "BIH"),
    BOTSWANA("Botswana", "BW", "BWA"),
    BRAZIL("Brazil", "BR", "BRA"),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", "IO", "IOT"),
    BRUNEI_DARUSSALAM("Brunei Darussalam", "BN", "BRN"),
    BULGARIA("Bulgaria", "BG", "BGR"),
    BURKINA_FASO("Burkina Faso", "BF", "BFA"),
    BURUNDI("Burundi", "BI", "BDI"),
    CAMBODIA("Cambodia", "KH", "KHM"),
    CAMEROON("Cameroon", "CM", "CMR"),
    CANADA("Canada", "CA", "CAN"),
    CAPE_VERDE("Cape Verde", "CV", "CPV"),
    CAYMAN_ISLANDS("Cayman Islands", "KY", "CYM"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "CF", "CAF"),
    CHAD("Chad", "TD", "TCD"),
    CHILE("Chile", "CL", "CHL"),
    CHINA("China", "CN", "CHN"),
    CHRISTMAS_ISLAND("Christmas Island", "CX", "CXR"),
    COCOS_ISLAND("Cocos Island", "CC", "CCK"),
    COLOMBIA("Colombia", "CO", "COL"),
    COMOROS("Comoros", "KM", "COM"),
    CONGO("Congo", "CG", "COG"),
    CONGO_DEMOCRATIC_REPUBLIC("Congo, The Democratic Republic of the", "CD", "COD"),
    COOK_ISLANDS("Cook Islands", "CK", "COK"),
    COSTA_RICA("Costa Rica", "CR", "CRI"),
    CROATIA("Croatia", "HR", "HRV"),
    CUBA("Cuba", "CU", "CUB"),
    CURACAO("Curaçao", "CW", "CUW"),
    CYPRUS("Cyprus", "CY", "CYP"),
    CZECH_REPUBLIC("Czech Republic", "CZ", "CZE"),
    DENMARK("Denmark", "DK", "DNK"),
    DJIBOUTI("Djibouti", "DJ", "DJI"),
    DOMINICA("Dominica", "DM", "DMA"),
    DOMINICAN_REPUBLIC("Dominican Republic", "DO", "DOM"),
    ECUADOR("Ecuador", "EC", "ECU"),
    EGYPT("Egypt", "EG", "EGY"),
    EL_SALVADOR("El Salvador", "SV", "SLV"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "GQ", "GNQ"),
    ERITREA("Eritrea", "ER", "ERI"),
    ESTONIA("Estonia", "EE", "EST"),
    ETHIOPIA("Ethiopia", "ET", "ETH"),
    FALKLAND_ISLANDS("Falkland Islands (Malvinas)", "FK", "FLK"),
    FAROE_ISLANDS("Faroe Islands", "FO", "FRO"),
    FIJI("Fiji", "FJ", "FJI"),
    FINLAND("Finland", "FI", "FIN"),
    FRANCE("France", "FR", "FRA"),
    FRENCH_GUIANA("French Guiana", "GF", "GUF"),
    FRENCH_POLYNESIA("French Polynesia", "PF", "PYF"),
    GABON("Gabon", "GA", "GAB"),
    GAMBIA("Gambia", "GM", "GMB"),
    GEORGIA("Georgia", "GE", "GEO"),
    GERMANY("Germany", "DE", "DEU"),
    GHANA("Ghana", "GH", "GHA"),
    GIBRALTAR("Gibraltar", "GI", "GIB"),
    GREECE("Greece", "GR", "GRC"),
    GREENLAND("Greenland", "GL", "GRL"),
    GRENADA("Grenada", "GD", "GRD"),
    GUADELOUPE("Guadeloupe", "GP", "GLP"),
    GUAM("Guam", "GU", "GUM"),
    GUATEMALA("Guatemala", "GT", "GTM"),
    GUINEA("Guinea", "GN", "GIN"),
    GUINEA_BISSAU("Guinea-Bissau", "GW", "GNB"),
    GUYANA("Guyana", "GY", "GUY"),
    HAITI("Haiti", "HT", "HTI"),
    HONDURAS("Honduras", "HN", "HND"),
    HONG_KONG("Hong Kong", "HK", "HKG"),
    HUNGARY("Hungary", "HU", "HUN"),
    ICELAND("Iceland", "IS", "ISL"),
    INDIA("India", "IN", "IND"),
    INDONESIA("Indonesia", "ID", "IDN"),
    IRAN("Iran, Islamic Republic of", "IR", "IRN"),
    IRAQ("Iraq", "IQ", "IRQ"),
    IRELAND("Ireland", "IE", "IRL"),
    ISRAEL("Israel", "IL", "ISR"),
    ITALY("Italy", "IT", "ITA"),
    JAMAICA("Jamaica", "JM", "JAM"),
    JAPAN("Japan", "JP", "JPN"),
    JORDAN("Jordan", "JO", "JOR"),
    KAZAKHSTAN("Kazakhstan", "KZ", "KAZ"),
    KENYA("Kenya", "KE", "KEN"),
    KIRIBATI("Kiribati", "KI", "KIR"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC("Korea, Democratic People's Republic of", "KP", "PRK"),
    KOREA_REPUBLIC("Korea, Republic of", "KR", "KOR"),
    KOSOVO("Kosovo", "XK", "KOS"),
    KUWAIT("Kuwait", "KW", "KWT"),
    KYRGYZSTAN("Kyrgyzstan", "KG", "KGZ"),
    LAOS("Laos", "LA", "LAO"),
    LATVIA("Latvia", "LV", "LVA"),
    LEBANON("Lebanon", "LB", "LBN"),
    LESOTHO("Lesotho", "LS", "LSO"),
    LIBERIA("Liberia", "LR", "LBR"),
    LIBYA("Libya", "LY", "LBY"),
    LIECHTENSTEIN("Liechtenstein", "LI", "LIE"),
    LITHUANIA("Lithuania", "LT", "LTU"),
    LUXEMBOURG("Luxembourg", "LU", "LUX"),
    MACAU("Macau", "MO", "MAC"),
    MADAGASCAR("Madagascar", "MG", "MDG"),
    MALAWI("Malawi", "MW", "MWI"),
    MALAYSIA("Malaysia", "MY", "MYS"),
    MALDIVES("Maldives", "MV", "MDV"),
    MALI("Mali", "ML", "MLI"),
    MALTA("Malta", "MT", "MLT"),
    MARSHALL_ISLANDS("Marshall Islands", "MH", "MHL"),
    MARTINIQUE("Martinique", "MQ", "MTQ"),
    MAURITANIA("Mauritania", "MR", "MRT"),
    MAURITIUS("Mauritius", "MU", "MUS"),
    MAYOTTE("Mayotte", "YT", "MYT"),
    MEXICO("Mexico", "MX", "MEX"),
    MICRONESIA("Micronesia, Federated States of", "FM", "FSM"),
    MOLDOVA("Moldova", "MD", "MDA"),
    MONACO("Monaco", "MC", "MCO"),
    MONGOLIA("Mongolia", "MN", "MNG"),
    MONTENEGRO("Montenegro", "ME", "MNE"),
    MONTSERRAT("Montserrat", "MS", "MSR"),
    MOROCCO("Morocco", "MA", "MAR"),
    MOZAMBIQUE("Mozambique", "MZ", "MOZ"),
    MYANMAR("Myanmar", "MM", "MMR"),
    NAMIBIA("Namibia", "NA", "NAM"),
    NAURU("Nauru", "NR", "NRU"),
    NEPAL("Nepal", "NP", "NPL"),
    NETHERLANDS("Netherlands", "NL", "NLD"),
    NEW_CALEDONIA("New Caledonia", "NC", "NCL"),
    NEW_ZEALAND("New Zealand", "NZ", "NZL"),
    NICARAGUA("Nicaragua", "NI", "NIC"),
    NIGER("Niger", "NE", "NER"),
    NIGERIA("Nigeria", "NG", "NGA"),
    NIUE("Niue", "NU", "NIU"),
    NORFOLK_ISLAND("Norfolk Island", "NF", "NFK"),
    NORTH_MACEDONIA("North Macedonia", "MK", "MKD"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", "MP", "MNP"),
    NORWAY("Norway", "NO", "NOR"),
    OMAN("Oman", "OM", "OMN"),
    PAKISTAN("Pakistan", "PK", "PAK"),
    PALAU("Palau", "PW", "PLW"),
    PALESTINE("Palestine", "PS", "PSE"),
    PANAMA("Panama", "PA", "PAN"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG", "PNG"),
    PARAGUAY("Paraguay", "PY", "PRY"),
    PERU("Peru", "PE", "PER"),
    PHILIPPINES("Philippines", "PH", "PHL"),
    PITCAIRN_ISLANDS("Pitcairn Islands", "PN", "PCN"),
    POLAND("Poland", "PL", "POL"),
    PORTUGAL("Portugal", "PT", "PRT"),
    QATAR("Qatar", "QA", "QAT"),
    ROMANIA("Romania", "RO", "ROU"),
    RUSSIAN_FEDERATION("Russian Federation", "RU", "RUS"),
    RWANDA("Rwanda", "RW", "RWA"),
    REUNION("Réunion", "RE", "REU"),
    SAINT_BARTHELEMY("Saint Barthélemy", "BL", "BLM"),
    SAINT_HELENA("Saint Helena", "SH", "SHN"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "KN", "KNA"),
    SAINT_LUCIA("Saint Lucia", "LC", "LCA"),
    SAINT_MARTIN("Saint Martin", "MF", "MAF"),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", "PM", "SPM"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "VC", "VCT"),
    SAMOA("Samoa", "WS", "WSM"),
    SAN_MARINO("San Marino", "SM", "SMR"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "ST", "STP"),
    SAUDI_ARABIA("Saudi Arabia", "SA", "SAU"),
    SENEGAL("Senegal", "SN", "SEN"),
    SERBIA("Serbia", "RS", "SRB"),
    SEYCHELLES("Seychelles", "SC", "SYC"),
    SIERRA_LEONE("Sierra Leone", "SL", "SLE"),
    SINGAPORE("Singapore", "SG", "SGP"),
    SINT_MAARTEN("Sint Maarten", "SX", "SXM"),
    SLOVAKIA("Slovakia", "SK", "SVK"),
    SLOVENIA("Slovenia", "SI", "SVN"),
    SOLOMON_ISLANDS("Solomon Islands", "SB", "SLB"),
    SOMALIA("Somalia", "SO", "SOM"),
    SOUTH_AFRICA("South Africa", "ZA", "ZAF"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia and the South Sandwich Islands", "GS", "SGS"),
    SOUTH_SUDAN("South Sudan", "SS", "SSD"),
    SPAIN("Spain", "ES", "ESP"),
    SRI_LANKA("Sri Lanka", "LK", "LKA"),
    SUDAN("Sudan", "SD", "SDN"),
    SURINAME("Suriname", "SR", "SUR"),
    SVALBARD_AND_JAN_MAYEN_ISLANDS("Svalbard and Jan Mayen Islands", "SJ", "SJM"),
    SWAZILAND("Swaziland (Eswatini)", "SZ", "SWZ"),
    SWEDEN("Sweden", "SE", "SWE"),
    SWITZERLAND("Switzerland", "CH", "CHE"),
    SYRIA("Syria", "SY", "SYR"),
    TAIWAN("Taiwan", "TW", "TWN"),
    TAJIKISTAN("Tajikistan", "TJ", "TJK"),
    TANZANIA("Tanzania", "TZ", "TZA"),
    THAILAND("Thailand", "TH", "THA"),
    TIMOR_LESTE("Timor-Leste", "TL", "TLS"),
    TOGO("Togo", "TG", "TGO"),
    TOKELAU("Tokelau", "TK", "TKL"),
    TONGA("Tonga", "TO", "TON"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "TT", "TTO"),
    TUNISIA("Tunisia", "TN", "TUN"),
    TURKEY("Turkey", "TR", "TUR"),
    TURKMENISTAN("Turkmenistan", "TM", "TKM"),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands", "TC", "TCA"),
    TUVALU("Tuvalu", "TV", "TUV"),
    UGANDA("Uganda", "UG", "UGA"),
    UKRAINE("Ukraine", "UA", "UKR"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE", "ARE"),
    UNITED_KINGDOM("United Kingdom", "GB", "GBR"),
    UNITED_STATES_OF_AMERICA("United States of America", "US", "USA"),
    URUGUAY("Uruguay", "UY", "URY"),
    UZBEKISTAN("Uzbekistan", "UZ", "UZB"),
    VANUATU("Vanuatu", "VU", "VUT"),
    VATICAN_CITY("Vatican City (Holy See)", "VA", "VAT"),
    VENEZUELA("Venezuela", "VE", "VEN"),
    VIET_NAM("Viet Nam", "VN", "VNM"),
    VIRGIN_ISLANDS_BRITISH("Virgin Islands, British", "VG", "VGB"),
    VIRGIN_ISLANDS_US("Virgin Islands, U.S.", "VI", "VIR"),
    WALLIS_AND_FUTUNA_ISLANDS("Wallis and Futuna Islands", "WF", "WLF"),
    WESTERN_SAHARA("Western Sahara", "EH", "ESH"),
    YEMEN("Yemen", "YE", "YEM"),
    ZAMBIA("Zambia", "ZM", "ZMB"),
    ZIMBABWE("Zimbabwe", "ZW", "ZWE");

    private final String name;
    private final String iso2Code;
    private final String iso3Code;

    //Map of iso3code to Country
    private static final Map<String, Country> iso3CodeMap = new HashMap<>();
    //initialize the map
    static {
        for (Country country : Country.values()) {
            iso3CodeMap.put(country.getIso3Code(), country);
        }
    }

    public static Country fromIso3(String iso3Code) {
        if (!iso3CodeMap.containsKey(iso3Code)) {
            return Country.UNKNOWN;
        }
        return iso3CodeMap.get(iso3Code);
    }

    Country(String name, String iso2Code, String iso3Code) {
        this.name = name;
        this.iso2Code = iso2Code;
        this.iso3Code = iso3Code;
    }

    public String getName() {
        return name;
    }

    public String getIso2Code() {
        return iso2Code;
    }

    public String getIso3Code() {
        return iso3Code;
    }
}