# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/experianplc/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
      working-directory: csharp/
    - name: Build
      run: dotnet build --no-restore --configuration Release DVSClient
      working-directory: csharp/
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    #   working-directory: csharp/
    - name: Pack
      run: dotnet pack --configuration Release DVSClient
      working-directory: csharp/
    - name: Publish
      run: dotnet nuget push "DVSClient/bin/Release/*.nupkg"
      working-directory: csharp/