# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: csharp/
    - name: Build
      run: dotnet build DVSClient.sln --no-restore
      working-directory: csharp/
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    #   working-directory: csharp/
    - name: Authenticate with registry
      run: dotnet nuget add source --username Experian --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text --name github "https://nuget.pkg.github.com/experianplc/index.json"
      working-directory: csharp/
    - name: Pack
      run: dotnet pack --configuration Release
      working-directory: csharp/
    - name: Publish
      run: dotnet nuget push "bin/Release/DVSClient.0.0.1.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
      working-directory: csharp/  