name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildDotNet:
    uses: ./.github/workflows/dotnet.yml

  increaseVersionNumber:
    runs-on: ubuntu-latest
    name: Increase version number

    steps:
      - uses: actions/checkout@v1
      - name: Script
        id: vars
        run: |
          $version = '${{ vars.SDKVERSION }}'
          $split_version = $version.split(".")
          $split_version[2] = [int]$split_version[2] + 1
          $sdkversion = $split_version -join "." 
          echo "sdkversion=$sdkversion" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        shell: pwsh
      - name: Set Repository Variable
        uses: action-pack/set-variable@v1
        with:
          name: 'SDKVERSION'
          value: ${{ steps.vars.outputs.sdkversion }}
          token: ${{ secrets.INCREASEVERSION }}