name: main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set Repository Variable
      # You may pin to the exact commit or the version.
      # uses: action-pack/set-variable@54de69c1565d1c9de606af2f1406814aa5d7551c
      uses: action-pack/set-variable@v1.13
      with:
        # Name
        name: SDKVERSION
        # Value
        value: 0.2.0
        # Repository name
        repository: edq-data-validation-sdks
        # Repository owner
        owner: experianplc
        # Flag for organization
        org: true
        # Repository access token
        token: ${{ secrets.GITHUB_TOKEN }}
          