name: main
run-name: main - ${{ vars.SDKVERSION }}

on:
  push:
    branches: [ "main" ]

jobs:
  buildDotNet:
    uses: ./.github/workflows/dotnet.yml
  buildJava:
    uses: ./.github/workflows/gradle.yml
  buildTypescript:
    uses: ./.github/workflows/typescript.yml
